### ISSUE TITLE
Fix 'TemplateRoot' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'.

### ISSUE THREAD

**Issue by itechy21** [Droidkit/OnePlus-One#2]
An exception that occurs at the launch of the GUI from the splash screen throws "'TemplateRoot' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'."
and uses mahapps to customise the UI
Need to figure out what is causing it and fix it...

**Comment by itechy21** [comment]
Fixed as of 1st September thanks to @punker76 for the fix :+1:

**Comment by itechy21** [comment]
pull request unfortunately didn't fix this issue but did improve the splash screen method so thanks for that :sunglasses:

**Comment by punker76** [comment]
@itechy21 it's now fixed with MaterialDesignThemes 0.0.0.104

**Comment by itechy21** [comment]
Thanks :) I shall update

**Comment by itechy21** [comment]
got the update but I cannot build as it is throwing a compilation error:
``Error	1	Invalid expression term ')'	C:\Users\James\documents\visual studio 2013\Projects\DroidKit OnePlus One\DroidKit OnePlus One\Splash.xaml.cs	72	14	DroidKit OnePlus One
``

**Comment by itechy21** [comment]
Fixed and reverted to old splash screen method
